apiVersion: 1
contactPoints:
  - orgId: 1
    name: "email receiver"
    receivers:
      - uid: "unique-id"
        type: "email"
        settings:
          addresses: "alexei.shulha@gmail.com"
        disableResolveMessage: false

